### ISSUE TITLE
Shed some light on segmented_cache design [DOC]

### ISSUE THREAD

**Issue by Zabrane** [esl/segmented_cache#11]
Hi guys and Happy New Year,

Can someone explain the `segmented_cache` internal design?

1. what's the purpose of using `process group` (pg)?
2. can we mix TTL and LRU for expiry?

An architecture design would be great.
Many thanks

**Comment by DenysGonchar** [comment]
Sorry for delay in response. I'm not sure if a separate document is really needed.

Here are the key points of design:
- TTL implementation notes:
   * cache is stored in a multiple ETS tables.
   * there's only one table use writing cache (active/current table).
   * tables are rotated and data from the last table is dropped.
   * TTL is not 100% accurate, I would interpret it as a warranty that cache record live less than `TTL` but at least `TTL - TTL/N` where N is a number of ETS tables.
   * there's a `gen_server` process, which is responsible for tables rotation (see `cache state notes` for more details).
- cache state notes:
   * persistent_term module is used to store cache state.
   * it's initialised just once and never changes after that.
   * there is a list of ETS tables - technically it's implemented as a tuple to improve access time.
   * there is an `atomic` ref that is used to track the index of the current (active) ETS table in the list (tuple).
   * `amotic` ref is constant, and it doesn't change
   * `atomic` value is changing, and what's important - changing in a lock free manner.
- LRU implementation notes:
   * on `is_member/2` and `get_entry/2` calls, record is reinserted in the current (active) ETS table.
- cache record deletion notes:   
   * in distributed environment, cache is populated independently on every node.
   * however, we must ensure that on deletion the cache record is removed on all the nodes (and from all the ETS tables, see `LRU implementation notes`)
   * there's a `gen_server` process responsible for ETS tables rotation (see `TTL implementation notes`)
   * the same process is reused to implement asynchronous cache record deletion on other nodes in the cluster.
   * in order to simplify discovery of these `gen_server` processes on other nodes, they all are added into a dedicated `pg` group.

@NelsonVides, please add your comments if I missed anything, otherwise - close this issue.

**Comment by Zabrane** [comment]
@DenysGonchar thank you very much.
